site_name: Local Quotes
repo_url: https://github.com/ka1tzyu/local-quotes
edit_uri: edit/master/docs/docs/

theme:
    name: material
    palette:
        - scheme: default
          toggle:
            primary: cyan
            accent: cyan
            icon: material/weather-sunny
            name: Switch to dark mode
        - scheme: slate
          toggle:
            primary: cyan
            accent: cyan
            icon: material/weather-night
            name: Switch to light mode
    logo: assets/obsidian.png
    favicon: assets/obsidian.png
extra_css:
    - assets/css/extra.css
nav:
    - Overview: 'index.md'
    - Features:
        - Quote listing: 'terms/quote-listings.md'
        - Search: 'terms/search.md'
    - Types of blocks:
        - Quote block: 'block-types/quote-block.md'
        - One-time quote block: 'block-types/one-time-quote-block.md'
    - Additional:
        - Quote Maker: 'additional/quote-maker.md'
        - Refresh helpers: 'additional/refreshing-blocks.md'
        - Statistics: 'additional/statistics.md'
    - Breaking changes:
        - Moving from 0.x.x to 1.x.x: 'breaking/moving-from-0.x.x-to-1.x.x.md'
