site_name: Local Quotes
repo_url: https://github.com/ka1tzyu/local-quotes
edit_uri: edit/master/docs/docs/

theme:
    name: material
    palette:
        primary: teal
        - scheme: default
          toggle:
            icon: material/material/weather-sunny
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/material/weather-night
            name: Switch to light mode
    logo: assets/obsidian.png
    favicon: assets/obsidian.png
nav:
    - Overview: 'index.md'
